# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 17:09
from __future__ import unicode_literals

import commenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commenter', '0002_auto_20170725_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'creation_date', 'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='firm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[commenter.models.Comment.validate_ZeroToFive]),
        ),
    ]
